SECTION TEXT
LABEL1: ADD ONE
LABEL2: SUB ONE
LABEL3: MUL ONE
LABEL4: DIV ONE
LABEL5: JMP ONE
LABEL6: JMPN ONE
LABEL7: JMPP ONE
LABEL8: JMPZ ONE
LABEL9: COPY ONE,TWO
LABELA: LOAD ONE
LABELB: STORE ONE
LABELC: STOP
LABELD: INPUT_C ONE
LABELE: OUTPUT_C ONE
LABELF: INPUT_S ONE,5
LABELF1: OUTPUT_S ONE,5
SECTION DATA
ONE: CONST 9
TWO: CONST 'a'
THREE: SPACE
FOUR: SPACE+20